In [ ]:
import pandas as pd
import numpy as np

df1=pd.DataFrame(np.array(range(1,26)).reshape(5,5),
             index=['a','b','c','d','e'],
             columns=['가','나','다','라','마'])

df1.loc['a','가':'라']
df1.iloc[0:3,2:4]
df1['가']
df1.가
df1['a':'c']
df1[0:2]

2. 타이타닉호 승객 데이터의 데이터 개수를 각 열마다 구해본다.
    결측값의 개수를 파악해본다

t=sns.load_dataset("titanic")
t.head()

t.info()
t.count()

na_num=[]
for i in range(len(t.columns)):
    na_num.append(sum(t.iloc[:,i].isna()))
na_num    

3. sort_values 메서드를 사용하여 타이타닉호 승객에 대해 
성별(sex) 인원수, 나이별(age) 인원수, 선실별(class) 인원수, 사망/생존(alive) 인원수를 구하라.

t.columns

features=['sex', 'age','pclass','survived']
for i in features:
    print(t[i].value_counts())


4.
타이타닉호 승객의 평균 나이를 구하라.
타이타닉호 승객중 여성 승객의 평균 나이를 구하라.
타이타닉호 승객중 1등실 선실의 여성 승객의 평균 나이를 구하라.

print(t.age.mean())
print(t.loc[t.sex=='female','age'].mean())
print(t.groupby('pclass').age.mean()[1])

5. 타이타닉호의 승객에 대해 나이와 성별에 의한 카테고리 열인 category1 열을 만들어라. category1 카테고리는 다음과 같이 정의된다.  
20살이 넘으면 성별을 그대로 사용한다.  
20살 미만이면 성별에 관계없이 “child”라고 한다.

t['category1']=t.apply(lambda x: 'adult' if x.age>20 else 'child',axis=1)

t.category1[t['category1']=='adult']= [i for i in t.sex[t['category1']=='adult']]

t['category1']

6.  
타이타닉호의 승객 중 나이를 명시하지 않은 고객은 나이를 명시한 고객의 평균 나이 값이   되도록 titanic 데이터프레임을 고쳐라.  

t.age[t.age.isna()]=t.age.mean()

7. 타이타닉호의 승객에 대해 나이와 성별에 의한 카테고리 열인 category2 열을 만들어라. category2 카테고리는 다음과 같이 정의된다.  
성별을 나타내는 문자열 male 또는 female로 시작한다.  
성별을 나타내는 문자열 뒤에 나이를 나타내는 문자열이 온다.  
예를 들어 27살 남성은 male27 값이 된다.  


t['category2']=[t.sex.iloc[i]+str(int(t.age.iloc[i])) for i in range(len(t))]

8.타이타닉호 승객을 ‘미성년자’, ‘청년’, ‘중년’, ‘장년’, ‘노년’ 나이 그룹으로 나눈다.  

bins = [1, 20, 30, 50, 70, 100]  
labels = ["미성년자", "청년", "중년", "장년", "노년"]  
그리고 각 나이 그룹의 승객 비율을 구한다. 비율의 전체 합은 1이 되어야 한다.  

bins = [1, 20, 30, 50, 70, 100]
labels = ["미성년자", "청년", "중년", "장년", "노년"]  
t['agecat']=pd.cut(t.age,bins,labels=labels)

(t['agecat'].value_counts()/len(t))
(t['agecat'].value_counts()/len(t)).sum()

9. 타이타닉호의 승객에 대해 나이와 성별에 의한 카테고리 열인 category3 열을 만들어라. category3 카테고리는 다음과 같이 정의된다.
20살 미만이면 성별에 관계없이 “미성년자”라고 한다.  
20살 이상이면 나이에 따라 “청년”, “중년”, “장년”, “노년”을 구분하고 그 뒤에   성별을 나타내는 “남성”, “여성”을 붙인다.  

t['category3']=np.where(t.age <20,'미성년자','성인')

t['category3'][t['category3']=='성인']=[i for i in t.agecat[t['category3']=='성인']]

10. (다중인덱스)  
A 반 학생 5명과 B반 학생 5명의 국어, 영어, 수학 점수를 나타내는 데이터프레임을 다음과 같이 만든다.  
“반”, “번호”, “국어”, “영어”, “수학” 을 열로 가지는 데이터프레임 df_score3을 만든다.  
df_score3을 변형하여 1차 행 인덱스로 “반”을 2차 행 인덱스로 “번호”을 가지는 데이터프레임 df_score4을 만든다.  
데이터 프레임 df_score4에 각 학생의 평균을 나타내는 행을 오른쪽에 추가한다.  
df_score3을 변형하여 행 인덱스로 “번호”를, 1차 열 인덱스로 “국어”, “영어”, “수학”을,   
2차 열 인덱스로 “반”을 가지는 데이터프레임 df_score5을 만든다.  
데이터 프레임 df_score5에 각 반별 각 과목의 평균을 나타내는 행을 아래에 추가한다.  


df_score3=pd.DataFrame({'반':['A','B','A','B','B'],
                        '번호':[1,1,2,3,4],
                        '국어':[50,40,60,70,50],
                        '영어':[100,80,50,70,30],
                        '수학':[50,60,70,20,90]})

df_score4=df_score3.set_index(['반','번호'])

df_score4['총합']=df_score4.apply(sum,axis=1)

df_score4['평균']=df_score4['총합']/len(df_score4)

df_score5=df_score4.unstack(1)

df_score5